import Head from "next/head";
import { useState } from "react";
import QRCode from "react-qr-code";
import Link from "next/link";

export default function Genarate() {
  const [qrCodeValue, setQrCodeValue] = useState("");
  return (
    <>
      <Head>
        <title>Generate QR</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-screen justify-center text-center">
        <div className="flex flex-col justify-center items-center">
          <h1 className="text-4xl font-bold mb-6">Generate QR</h1>
          {qrCodeValue != "" && <QRCode value={qrCodeValue} className="mb-6" />}
          <input
            className="border border-gray-400 p-2 rounded-lg"
            onChange={(e) => {
              setQrCodeValue(e.target.value);
            }}
            placeholder="Try typing..."
          />
          <Link
            href={`/`}
            className=" bg-orange-200 m-4 text-md rounded-md px-4 py-2 hover:underline"
          >
            Back to home..
          </Link>
        </div>
      </main>
    </>
  );
}
