import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col h-screen justify-center items-center">
        <div className="flex flex-col lg:flex-row">
          <Link
            href={`/scan`}
            className=" bg-red-200 m-4 text-4xl rounded-md px-4 py-2 hover:bg-blue-400"
          >
            QR Scan
          </Link>
          <Link
            href={`/generate`}
            className=" bg-orange-200 m-4 text-4xl rounded-md px-4 py-2 hover:bg-green-400"
          >
            QR Genarate
          </Link>
        </div>
      </main>
    </>
  );
}
